app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :members
  root 'members#index'
  get 'home/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/app/models/member.rb
class Member < ApplicationRecord
    belongs_to :user
end

app/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :members
end

app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [ :show, :edit, :update, :destroy ]
  # If you are not the user who creates the member, you are not authorized to edit it.
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /members or /members.json
  def index
    @members = Member.all
  end

  # GET /members/1 or /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = current_user.members.build
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members or /members.json
  def create
    @member = current_user.members.build(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to member_url(@member), notice: "Member was successfully created." }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1 or /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to member_url(@member), notice: "Member was successfully updated." }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1 or /members/1.json
  def destroy
    @member.destroy!

    respond_to do |format|
      format.html { redirect_to members_url, notice: "Member was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
      @member = current_user.members.find_by(id: params[:id])
      redirect_to members_path, notice: "Not Authorized to Edit This Member" if @member.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def member_params
      params.require(:member).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/app/helpers/application_helper.rb
module ApplicationHelper
end

app/app/helpers/home_helper.rb
module HomeHelper
end

app/app/helpers/members_helper.rb
module MembersHelper
end

app/app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to 'Our Team', root_path, class:"navbar-brand" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item mr-2">
        <%= link_to 'About Us', home_about_path, class:"nav-link" %>
      </li>

    <% if user_signed_in? %>

        <li class="nav-item mr-2">
        <%= link_to 'Add Member', new_member_path, class:"nav-link" %>
        </li>

     <li class="nav-item mr-2">
        <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
     </li>

        <li class="nav-item mr-2">
         <%= link_to 'Sign-out', destroy_user_session_path, data: {turbo_method: :delete}, class:"nav-link" %>
        </li>

    <% else %>
        <li class="nav-item mr-2">
            <%= link_to 'Sign-up', new_user_registration_path, class:"nav-link" %>
        </li>

        <li class="nav-item mr-2">
            <%= link_to 'Sign-in', new_user_session_path, class:"nav-link" %>
        </li>

    <% end %>




    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/app/views/home/about.html.erb
<h1>About Us</h1>

<p>
We started Defang because, as practitioners with experience in both building cloud apps and cloud platforms, we were unhappy with the state of the art. It remains too difficult to create, deploy, and manage cloud applications. In architecting and building a cloud app, developers need to consider a multitude of factors such as performance, scalability, cost, portability, flexibility, simplicity, etc. At the same time, they face a bewildering array of choices - across application architecture, choice of cloud platforms and services, configuration and deployment settings etc. - that most developers are clearly not the experts in. Clearly, we need a better way.

Improving on this state of affairs is a long journey. It starts by making it radically simpler to create and deploy cloud apps, helping developers to get from idea to deployed app as quickly as possible. We do this by removing as much unnecessary complexity as possible. For example, by leveraging the power of Generative AI, we enable you to instantaneously go from a natural language prompt to initial project outline and code. Once you are done refining that code, we enable you to deploy it to your own cloud account with a single command, with all the proper configuration, security etc. With these capabilities, we make cloud app development a whole lot simpler and accessible to a much broader audience of developers.

This is only the beginning. To make cloud app development truly powerful, it must support the ability to easily evolve app architectures, be portable across different clouds, and offer much higher levels of resilience. These are some of the longer-term objectives we will be working on. We welcome you to join us on this journey!
</p>

app/app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <title>Team Homepage</title>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>

      <br></br>

     <%= yield %>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

app/app/views/members/_form.html.erb
<%= form_with(model: member) do |form| %>
  <% if member.errors.any? %>
    <div style="color: red">
      <h5><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h5>

      <ul>
        <% member.errors.each do |error| %>
          <li class="text-danger"><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name, class:"form-control", placeholder:"AK" %>
  </div>

  <div class="field form-group">
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name, class:"form-control", placeholder:"Kai" %>
  </div>

  <div class="field form-group">
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, class:"form-control", placeholder:"abc@gmail.com" %>
  </div>

  <div class="field form-group">
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone, class:"form-control", placeholder:"562413" %>
  </div>

  <div class="field form-group">
    <%= form.label :twitter, style: "display: block" %>
    <%= form.text_field :twitter, class:"form-control", placeholder:"@AKAKKAKAK" %>
  </div>

  <div class="action">
    <%= form.submit %>
  </div>
<% end %>

app/app/views/members/edit.html.erb
<h1>Editing member</h1>

<br>

<%= render "form", member: @member %>

<br>

<div>
  <%= link_to "Show this member", @member, class:"btn btn-secondary" %> |
  <%= link_to "Back to members", members_path, class:"btn btn-black" %>
</div>

app/app/views/members/index.html.erb
<table class="table table-striped table-bordered table-hover">
  <thread class="thread-dark">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Twitter</th>
      <th> </th>
    </tr>
  </thread>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= link_to member.first_name + ' ' + member.last_name, member %></td>
        <td><%= member.email %></td>
        <td><%= member.phone %></td>
        <td><%= member.twitter %></td>
        <td><%= link_to 'Delete', member_path(member), data: { turbo_method: :delete, turbo_confirm: 'Are you sure' } , class: "btn btn-outline-danger btn-sm" %></td>
       # has to have a td to let this row be in the table, otherwise it will appear at the top

      </tr>

    <% end %>

  </tbody>

</table>


<%= link_to "New member", new_member_path, class:"btn btn-secondary" %>

app/app/views/members/new.html.erb
<h1> Add New member</h1>

<%= render "form", member: @member %>


<br>

<div>
  <%= link_to "Back to members", members_path, class:"btn btn-dark"%>
</div>

app/app/views/members/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">Hello <%= @member.first_name%> </h1>
  <p><%= @member.email%> | <%= @member.phone%> | <%= @member.twitter%></p>
  <hr class="my-4">
  <%= link_to "Edit this member", edit_member_path(@member), class:"btn btn-secondary" %> |
  <%= link_to "Back to members", members_path, class:"btn btn-secondary" %>

  <br></br>
  <%= button_to "Destroy this member", @member, method: :delete %>

</div>